dist: trusty
sudo: required
before_install:
language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py install
- pip install coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- coverage run --source=twintel ./test_script.py
after_success: coveralls
deploy:
  provider: pypi
  user: mikkokotila
  password:
    secure: NomuQq72VnXYHyurVbThOtx5aY2kl5Q+gul1rzXjf/wlMfSspigsuV4Rm+MXjS9DSVshLwwIfQ8RMmx8EES2u28F4QcbxvccRHnKTN/QYkYXwQcJS7ckx2WVNSpQY1wgSNdGhl1mlkpic2S8wn72bU/6VyzYvBdD0394GaoWyhOjQ69R4V9/YBYmmZBfqAgprAEC207ECSaLQtfboh3EB6P8/tAHNxKn0dgAmXopZxKtW9wUdy0oOLn0ECFG5ftQ7YFo9YwZGseHKXOxji4bzHSnXwZhHBR24uwuT6VywvkmI8/hkSfoBNiotOkZ2CzB4nx/bqvCfbw7IPRkHlDGiCc4IfnNu+V/Sw3sAgtm/+Ykgpc5gPtwhQAeDlB3Shi3ZHNhGLYTVs2aH3AvLS5+u2xV5ouuNaDed8qQCeWUl43qTaSoMPYVh1AuHyybEzVpG8aMAcP08tQHI04zK0okBzavW2IJW41vcLkRXVrQsiZDrT4o/yn17LH76FY6RQ5Qp4gmwPRjzTrQL2A3g3YDCidClefD5YcNU7VwZ+qG1Da7xO3Y7WedCZrz7uBmFsmq9HdXzBCrQASzVfXOgGgRHUyZHdUUYzdPAY+kJYiLkJjG8CH3sEAi0/rlPGQmtk3oDOitYWdn8/wtqIR060LIi1tfhZsYEq2E+c9ElKIpoVw=
  on:
    branch: production
